### ISSUE TITLE
NativeSocket::__construct should enable TCP keepalive

### ISSUE THREAD

**Issue by jhammer** [pda/pheanstalk#105]
If Pheanstalk has dispatched a reserve command and is just waiting for
a response, it will never timeout if there is a network partition or
the beanstalkd server panics. Setting SO_KEEPALIVE allows Pheanstalk to
be made aware of these events (subject to the operating system’s
keepalive settings)

Recommend adding the following call in NativeSocket::__construct

``` php
socket_set_option( socket_import_stream( $this->_socket ), SOL_SOCKET, SO_KEEPALIVE, 1 );
```

**Comment by matang-dave** [comment]
Hi, I faced the same issue . 
But socket_set_option work only with socket_create() or socket_accept(), and here library  is using fsocket for socket connections.
Ref : [php manual](http://php.net/manual/en/function.socket-set-option.php). 
Did you get success using it ?

I have achieved this by using stream_set_timeout() . I check if timed out or not using stream_get_meta_data . If i am getting some continues time outs , i conclude  there is some issue and try to re-connect .

To prevent  false time-out with reserve command , i use reserve command with timeout which is less then stream_set_timeout() . 

Please share if you have any better approach ...

**Comment by SamMousa** [comment]
This would require using (and thus depending on) the socket extension.
Since there is no way to set the keep alive option when using `fsockopen` I'm closing this for now.

If there is such an option feel free to reopen it.
