### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by umajeric** [pda/pheanstalk#115]
Is there any plan to draft a new release soon? Some functionality would be needed in production that is on master branch.

**Comment by GrahamCampbell** [comment]
The next release is 3.0.0. Not sure if there's still incomplete stuff.

**Comment by umajeric** [comment]
Was not 3.0.0 release already made (https://github.com/pda/pheanstalk/releases/tag/v3.0.0)? Any dates for the release?

**Comment by GrahamCampbell** [comment]
Oh right. :)

**Comment by GrahamCampbell** [comment]
:+1: for a 3.0.3 release then.

**Comment by pda** [comment]
Thanks for the reminder, here we go: https://github.com/pda/pheanstalk/releases/tag/v3.1.0

**Comment by GrahamCampbell** [comment]
The branch alias is wrong then. It still says 3.0.x.

**Comment by pda** [comment]
Also as usual I forgot to bump `Pheanstalk::VERSION` ;)
It was about time for a 3.1.1 release, anyway.

**Comment by GrahamCampbell** [comment]
Maybe you should just remove that constant. Seems pretty pointless to me.

**Comment by GrahamCampbell** [comment]
Well, remove in 4.x anyway. Bit late for 3.x.
