### ISSUE TITLE
the beanstalkd() bury method

### ISSUE THREAD

**Issue by BardiaAfshin** [pda/pheanstalk#124]
I want to delete a job that's been attempted more than 3 times, I read on a laracast forum that beanstalkd specifically provides this functionality via bury() method, however I don't see any docs on this for pheanstalk.

I'm working within the Laravel framework (5.0), any documentation shared would be most helpful.

**Comment by pda** [comment]
Here's the [Bury command class](https://github.com/pda/pheanstalk/blob/ba8c8b1c3265d4a925864bfffe04c806c3364803/src/Command/BuryCommand.php) and the [$pheanstalk->bury($job, $priority)](https://github.com/pda/pheanstalk/blob/ba8c8b1c3265d4a925864bfffe04c806c3364803/src/Pheanstalk.php#L59) facade method which uses it.

Pretty much everything is available via the top-level `Pheanstalk` class which you can read at https://github.com/pda/pheanstalk/blob/master/src/Pheanstalk.php

Note there's also a `delete` command which you'd use if you never wanted to access that job again. Buried jobs can be inspected and [kicked](https://github.com/pda/pheanstalk/blob/ba8c8b1c3265d4a925864bfffe04c806c3364803/src/Pheanstalk.php#L90) back to life.

The official beanstalkd protocol documentation is at https://raw.githubusercontent.com/kr/beanstalkd/master/doc/protocol.txt too.
