### ISSUE TITLE
Which branch is considered latest stable?

### ISSUE THREAD

**Issue by rparsi** [pda/pheanstalk#126]
I see the 'master' branch and '2.1', which of the two is considered the latest and most stable?
It's not clear from the documentation.

**Comment by pda** [comment]
There is no stable branch, [only tagged releases](https://github.com/pda/pheanstalk/tags). `master` is the latest development branch. The `2.1` branch was created to backport a fix onto v2.1.0 to create v2.1.1 when `master` had already moved onto v3.x.
