### ISSUE TITLE
Add callbacks/support for libevent

### ISSUE THREAD

**Issue by dekker-m** [pda/pheanstalk#130]
**The idea**
I would be great to have support for a callback in the reserve method. The callback would receive the reserved job. With libevent it could be fairly easy to implement the callback method. Not just for reserving a job, basically for any other operation as well. I haven't checked the full code at the moment, but this should be possible by implementing a new socket which uses libevent for I/O. The main class should get callback parameters for every method, and, if no callback parameter is provided, it can disable the event handler for libevent, so the code doesn't break any compatibility. (Or enabling/disabling the event handler should probably be implemented in the Connection class's dispatch method).

_Are more people interested in this? I won't have any time left this week, but if there is support for this issue and the developers are interested as well, I could check if I can make the changes myself next week._

**Why?**
We are migrating to beanstalkd for our long running tasks. At the moment most long running tasks are executed by long running processes, which fork the process for every new job. The problem is, the processes do not look at the load of the server when starting new jobs and still have to query the database/filesystem for new jobs.

So, we decided to create a central process manager which launches new jobs when they become available in beanstalkd. This central process manager starts jobs based on the system load/memory usage of the server it is running on and other dependent servers (SQL database, ElasticSearch, NFS, etc.). A new job is created by forking the processes and starting the job in the child process.

This is where the callback method would come in handy. Our process manager needs to keep track of the system load/memory usage of multiple servers and needs to clean up after finished processes. In other words: if we request a job from beanstalkd, it will block till a new job is available. During this time it cannot do any of its other tasks.

PS: I know the reserve method has a timeout parameter, but I thought this was a more elegant solution.

**Comment by SamMousa** [comment]
Closed due to lack of interest.
