### ISSUE TITLE
Sleeping  time when queue is empty

### ISSUE THREAD

**Issue by niknickolas** [pda/pheanstalk#131]
Hi, is there way set time for sleeping when queue is empty.
 https://github.com/pda/pheanstalk/blob/master/src/Socket/NativeSocket.php#L20
https://github.com/pda/pheanstalk/blob/master/src/Socket/NativeSocket.php#L49

**Comment by raulp** [comment]
You could use watch( YOUR_TUBE )->reserve( TIMEOUT )

**Comment by SamMousa** [comment]
I'm closing this issue.
If you're reserving jobs you can either use blocking calls meaning your application is effectively automatically sleeping.
If you want to do non-blocking checks repeatedly, sleeping is the responsibility of application code.
