### ISSUE TITLE
Is there a way to check whether specific tube is empty?

### ISSUE THREAD

**Issue by slier81** [pda/pheanstalk#145]
As title, is there a way?

**Comment by pda** [comment]
You could see if `$pheanstalk->statsTube($name)->current_jobs_ready` is zero, or you could `$job = $pheanstalk->reserve(0);` (zero timeout; non-blocking reserve) and see if $job is `false`, but then you'd potentially have a job reserved.

**Comment by slier81** [comment]
thanks for your answer
