### ISSUE TITLE
Socket error 111: Connection refused (connecting to 127.0.0.1:11300) 

### ISSUE THREAD

**Issue by zplzpl** [pda/pheanstalk#153]
i have three tube.

two tube work is good, but have one tube it get this error:
Socket error 111: Connection refused (connecting to 127.0.0.1:11300) 

i don't understand.

can you help me?

**Comment by nodefish** [comment]
Not sure if this might help, but temporarily try running beanstalkd as root:
`beanstalkd -u root`

This resolved "connection refused" errors for me from remote connections. For a more permanent solution, a separate account should be made for beanstalkd, but I haven't figured out the proper permissions yet (I'm guessing the permission issue is related to writing to the binlog).

**Comment by zplzpl** [comment]
oh,thank you for you job.
I have no problem.
