### ISSUE TITLE
Fatal error: Uncaught exception 'Pheanstalk\Exception\ConnectionException' 

### ISSUE THREAD

**Issue by xujiajun** [pda/pheanstalk#156]
hi,  i try to connect beanstalkd

but   it not work:

```
Fatal error: Uncaught exception 'Pheanstalk\Exception\ConnectionException' with message 'Socket error 110: Connection timed out (connecting to 172.0.0.1:11300)' in /var/release/20161010-160915/vendor/pda/pheanstalk/src/Socket/NativeSocket.php:45
```

i have try telnet 127.0.0.1 11300

![image](https://cloud.githubusercontent.com/assets/6065007/19516752/0d05eb30-9630-11e6-9531-b1b672c7eef8.png)

and i try command :ps aux |grep 'beanstalkd' process is alive

![image](https://cloud.githubusercontent.com/assets/6065007/19516853/a9b04db8-9630-11e6-8610-768bf6dce41d.png)

ps: my dev environment： ubuntu 14.04

who can give me help,thanks a lot.

**Comment by xujiajun** [comment]
i have solved the problem. please close this issure.

**Comment by filipesiqueira** [comment]
Where's the solution, @xujiajun ?

**Comment by xujiajun** [comment]
@filipesiqueira it's my problem.its OK now .please close this issues
