### ISSUE TITLE
NativeSocket.php - stream timeout

### ISSUE THREAD

**Issue by adrianwaler** [pda/pheanstalk#162]
Hello,

Sorry for new issue, but previous topic is very very old.

Problem is that in current version stream timeout not working, so if queue is empty then we have infinity loop. There are 3 PR to fix it. Is there any possibility to merge one of them? I don't see any sense of creating new one.

Previous issue: #13 
Pull requests:
* #152 
* #138 
* #95 

Thanks!

**Comment by SamMousa** [comment]
> I don't see any sense of creating new one.

I agree, same goes for issues though.  ;-)

I'm considering merging #163 to fix the issue, any feedback you have is welcome there!
