### ISSUE TITLE
Why do i have to restart beanstalkd service again and again

### ISSUE THREAD

**Issue by sarvesh-esokia** [pda/pheanstalk#166]
Hi, I am new to Beanstalkd and chose using the pheanstalk client. I have separated both code for producer and worker

**producer.php**
```
include 'vendor/autoload.php';

use Pheanstalk\Pheanstalk;

$pheanstalk = new Pheanstalk('127.0.0.1');

// ----------------------------------------
// producer (queues jobs)

$pheanstalk
  ->useTube('testtube')
  ->put("job payload goes here\n");
```

**worker.php**
```
include 'vendor/autoload.php';

use Pheanstalk\Pheanstalk;

$pheanstalk = new Pheanstalk('127.0.0.1');
$job = $pheanstalk
  ->watch('testtube')
  ->ignore('default')
  ->reserve();

echo $job->getData();

$pheanstalk->delete($job);
```

My issue is that the first time I run producer.php and worker.php, it works but if i again run worker.php it fails, until I don't do `sudo service beanstalkd restart`. Have i missed anything on the worker's code, Please advise. 

Thanks

**Comment by alister** [comment]
How are you starting the beanstalkd server? The code you have there is very ordinary and would not easily effect the server itself.

**Comment by sarvesh-esokia** [comment]
I've have installed beanstalkd on my Ubuntu 16.04. It starts automatically on start-up i guess.

**Comment by alister** [comment]
Github issues are not the best place for tech-support. I suggest closing this thread, and put more details on how you start and use the server onto StackOverflow.

**Comment by sarvesh-esokia** [comment]
Thanks for the reply @alister, the beanstalkd service is already ON when I boot on my ubuntu 16.04. Its been this ever since I installed it.
