### ISSUE TITLE
laravel5.4,php7,centos7

### ISSUE THREAD

**Issue by maokeyang** [pda/pheanstalk#168]
i got a problem, when i try to connect. it has this error:
` Pheanstalk\Exception\ConnectionException: Socket error 0:  (connecting to 127.0.0.1:11300) in /www/xxx/vendor/pda/pheanstalk/src/Socket/NativeSocket.php:45`

But i run command `telnet  127.0.0.1 11300 ` is ok.please help me

**Comment by spyp** [comment]
i already used in php 7 centos 7 and laravel 5.2 5.5 and 5.6 ant its ok with all of them.
perhaps you have problem with server package not this package

**Comment by SamMousa** [comment]
This is not a bug report.
