### ISSUE TITLE
is this project dead ?

### ISSUE THREAD

**Issue by mkingbe** [pda/pheanstalk#169]
Hello,

@pda I'he seen that there are no commits from Sep 22, 2016 also that there are 28 opened issues and 11 pull requests. Is this project dead?

**Comment by pda** [comment]
I'm no longer using nor maintaining it.
I'd be happy to see other people maintain it.

**Comment by SamMousa** [comment]
@pda bump!

**Comment by dmcfaul** [comment]
I'm interested in being a maintainer for this package. I use it pretty extensively at the moment. @pda could you add @SamMousa and I as collaborators to the project?

**Comment by pda** [comment]
I've added @SamMousa for now, based on strong history of GitHub activity.

I also added @jimbojsb as he's previously contributed and [expressed interest](https://github.com/pda/pheanstalk/issues/79#issuecomment-33520002) (although that was four years ago now!).

@dmcfaul nothing personal but I need to know you're not a repo-hijacking bot before giving you access ;) Commit access to shared libraries like this is a worrying attack vector for a lot of systems. Perhaps if you get a commit merged by one of these new collaborators or something?

**Comment by SamMousa** [comment]
Thanks! I'll start reviewing PRs on Monday.

**Comment by SamMousa** [comment]
@pda In case you ever want to contact me on skype: sam_mousa 
(in case you disagree with any choices I make ;-))

**Comment by SamMousa** [comment]
We now have 2 contributors and 1 interested party @dmcfaul.

Meaning we can conclude the project is not dead.
