### ISSUE TITLE
Any plan to support multiple servers?

### ISSUE THREAD

**Issue by chadkouse** [pda/pheanstalk#17]
Would be nice to give pheanstalk an array of server ip's and ports and have it just randomly (or even not so randomly) choose which one to send the job to.  This would eliminate all of the developers who use pheanstalk from having to roll their own sharding solution.

**Comment by hugochinchilla** [comment]
Pinging all the people who subscribed to this topic, still interested on this? I would like to discuss some ideas, I'm implemeting a HA version of this client (not the same from #110), before making a pull request i would like to discuss the approach I'm taking.

Here there is a piece from a docstring explaining how my approach works, totally open to criticism and new ideas.

```php
/**
 * HighAvailability Pheanstalk client.
 *
 * This client allows using multiple beanstakd servers. The behavior is experimental and subject
 * to change. There is a different behavior for producers and consumers:
 *
 *  - Producers will put all jobs on the first working connection the found, when an error is found
 *    they will start using the next connection available and keep using that connection until
 *    another error happens.
 *
 *  - Consumers will start reserving jobs from the first working server, until an error happens or a
 *    timeout is reached (a timeout is forced if not specified, explained later) in any of both
 *    scenarios the consumer will open a connection to the next server and try to reserve from it.
 *
 * Timeouts are forced on every reserve command to force consumers to jump from one server to
 * another when they cannot find a job, this way we can be sure that at any time all server queues
 * are going to be consumed and no tasks are going to be left forgotten. If your queues are never
 * emptied, then you should try adding more consumers or this implementation will not work at all
 * for you.
*/
```

**Comment by SamMousa** [comment]
@hugochinchilla I feel that this is a niche that, while nice, should not be part of base classes of this library.
If you want to add new class that use composition to implement it I'll review a PR.

Based on the age of this issue i'm closing it for now, if you want to start working on a PR just open one with a reference to this issue. Feel free to open it as soon as you start (just add WIP in front of the PR name).
