### ISSUE TITLE
Split reserve into 2 functions

### ISSUE THREAD

**Issue by SamMousa** [pda/pheanstalk#178]
Currently `reserve()` has an optional timeout parameter.
This leads to an optional return type; since if a timeout happens no exception is thrown yet we don't get a `Job` as return value.

I propose:
- Change `reserve()` to:
```php
/** @throws someException **/
public function reserve(): Job
```
- Add `reserveWithTimeout`:
```php
/** 
    @throws someException 
    @throws TimeoutException
**/
public function reserveWithTimeout(int $timeout): Job
```

**Comment by alister** [comment]
Another option could be with a Null Object pattern - a subclass of Job that has no contents. Its a little cleaner than a nullable job (`function reserve(): ?Job`), which is possible from PHP 7.1.

**Comment by alister** [comment]
It's not an exceptional event if the queue is empty and equally, a reserve could end up not returning a job either with socket timeouts - or other fairly ordinary issues. So, not having a job to work on is an event that should be handled - not normally as a particular problem though. 

I've written code that would pause for a little longer than usual on an empty queue, especially if it's not likely to be urgent, or there will often be large gaps between things to do.

**Comment by SamMousa** [comment]
> either with socket timeouts - or other fairly ordinary issues.
These issues are already exceptions, and they should be...
