### ISSUE TITLE
Connection problem adding more 100k jobs to beanstalkd

### ISSUE THREAD

**Issue by prox** [pda/pheanstalk#26]
Hi,

PHP does not close the connections properly i don't know, when I'm adding more 100k jobs to the queue with pheanstalk. I checked your code and made some changes on it, letting it use a "persistant" connection (keeping socket).

I cannnot attach files here, so if you want take a look at my changes, send me an email and I will provide you the changes :)

Regards,
Sven

**Comment by SamMousa** [comment]
Closing this, persistent connection support was added in #90
