### ISSUE TITLE
Option to specify Default Tube

### ISSUE THREAD

**Issue by munirehmad** [pda/pheanstalk#36]
The current implementation creates an extra tube which is default tube and I can't find a good way to change it to whatever name I please other than changing the Hardcoded constant.

I suggest that while creating connection you should be able to pass the default tube name (optional) which will make pheanstalk watch that specific tube.

Let me know what you think,

Regards,
Munir

**Comment by SamMousa** [comment]
https://github.com/beanstalkd/beanstalkd/blob/master/doc/protocol.txt#L112

This is actually just something that indicates the default behavior of the protocol.

If you want to use a different name you should call the relevant functions after initialization.
