### ISSUE TITLE
Pheanstalk needs maintainer(s)

### ISSUE THREAD

**Issue by pda** [pda/pheanstalk#79]
Many people are using Pheanstalk, but I haven't been able to give it the attention it deserves.

I'd love to take on one or more maintainer (two sounds like a good number) to help push it forwards.

Anybody interested?

Let me know in what capacity you use Pheanstalk (e.g. for what purpose, at what company etc) _[Optional. And be as vague or specific as you want]_.
And also what kind of changes you'd like to push forwards, or if you'd rather just work on fixing general maintenance issues that arise.

Cheers,
Paul

**Comment by Dandroas** [comment]
I'd like to volunteer!

**Comment by mohitjawanjal14** [comment]
Is this still open? I'd like to contribute.

**Comment by airoude** [comment]
I would also like to actively contribute.

**Comment by SamMousa** [comment]
Everyone who posted they want to contribute, I'll be happy to review any suggestions and PRs.
I've labeled issues that with the `ready for adoption` label in case the proposed approach is acceptable.
Feel free to submit PRs!
