### ISSUE TITLE
No CLRF at the end of data

### ISSUE THREAD

**Issue by korys** [pda/pheanstalk#96]
Hi,
I run into this issue:

<pre>exception 'Pheanstalk_Exception_ClientException' with message 'Expected 2 bytes of CRLF after 566 bytes of data' in /data/www/myproject/library/pheanstalk/classes/Pheanstalk/Connection.php:104</pre>

I understand that is caused by incorrectly writtne data, but have no idea, why data was written incorrectly. It's looks like rare case, but it leads to more problems.
My consumer tries to consume this job every loop with no luck, until I run out of memory because of other jobs increasing queue.

It's looks like it is not possible to delete this job, because I can't get its ID without rising an exception. Now I'm deleting incorect job manually, bu how can I do that using Pheanstlak? 

I'm using beanstlkd ver. 1.10 and Pheanstalk ver 2.1.0

**Comment by pkruithof** [comment]
I'm also having this issue (beanstalkd 1.9, Pheanstalk 2.1.0). 

Inspection shows that on occasions, jobs only containing NULL bytes are added. I don't know if this is caused by my application, Pheanstalk, or beanstalkd itself, but it does occur and it makes my consumer stuck due to the exception.

```sh
$ beanstool peek --state ready
id: 8574620, length: 6, priority: 1024, delay: 0, age: 90268, ttr: 1200
reserves: 46, releases: 0, buries: 0, kicks: 0, timeouts: 0
body:
"\x00\x00\x00\x00\x00\x00
```

**Comment by DavidGoodwin** [comment]
For anyone in the future who hits this problem; the only way I could solve it was to telnet to the beanstalk instance, and call delete on the job. e.g.

```
telnet server 11300
Trying 192.168.0.1......
Connected to 192.168.0.1.
Escape character is '^]'.
use the_tube
USING the_tube
peek-ready
FOUND 1532266225 284
{ json that's randomly terminated and not valid 
delete 1532266225
DELETED
peek-ready
FOUND 12345678 287
{ valid json ... }
```

Where FOUND 1532266225 284 is [JOBID] [BYTE SIZE] .. so DELETE 1532266225 removes it.

**Comment by SamMousa** [comment]
This is the same as #111 .
